
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpass = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        ex = new javax.swing.JButton();
        up = new javax.swing.JButton();
        in = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel6.setText("jLabel5");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/floral-brushes27.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 120, 61, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 40, 70, 30);

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass);
        txtpass.setBounds(110, 150, 200, 30);

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnama);
        txtnama.setBounds(110, 70, 200, 30);

        ex.setBackground(new java.awt.Color(255, 102, 102));
        ex.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ex.setText("Exit");
        getContentPane().add(ex);
        ex.setBounds(160, 200, 80, 30);

        up.setBackground(new java.awt.Color(102, 255, 153));
        up.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        up.setText("Sign Up");
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });
        getContentPane().add(up);
        up.setBounds(60, 200, 80, 30);

        in.setBackground(new java.awt.Color(153, 153, 255));
        in.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        in.setText("Sign In");
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });
        getContentPane().add(in);
        in.setBounds(260, 200, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/aaa.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 250, 400, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 200, 230, 120);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel7.setText("jLabel5");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, -30, 230, 120);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel8.setText("jLabel5");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 40, 230, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel9.setText("jLabel5");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 200, 230, 120);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel10.setText("jLabel5");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 110, 230, 120);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel11.setText("jLabel5");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 70, 230, 120);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel12.setText("jLabel5");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 110, 230, 120);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel13.setText("jLabel5");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(160, 0, 230, 120);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel14.setText("jLabel5");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 110, 230, 120);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel15.setText("jLabel5");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(-10, -30, 230, 120);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel16.setText("jLabel5");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-10, -30, 230, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ok.JPG"))); // NOI18N
        jLabel17.setText("jLabel5");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(160, 70, 230, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
       String username = txtnama.getText();
        String password = txtpass.getText();
        
        try {
            try(Statement statement = (Statement) file_koneksi.GetConnection().createStatement()) {
                statement.executeUpdate("insert into tb_akun(username,password) VALUES ('"+username+"','"+password+"');");
            } 
            JOptionPane.showMessageDialog(null,"Selamat! Anda berhasil Sign Up!");
        }
        catch (Exception t) {
            JOptionPane.showMessageDialog(null,"Mohon Maaf, Ulangi lagi prosedurnya!");
        }
    }//GEN-LAST:event_upActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
        Connection connection;
        PreparedStatement ps;
        try{
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_testkoneksi?zeroDateTimeBehavior=convertToNull", "root", "");
            ps = connection.prepareStatement("SELECT `username`, `password` FROM `tb_akun` WHERE `username` = ? AND `password` = ?");
            ps.setString(1, txtnama.getText());
            ps.setString(2, txtpass.getText());
            ResultSet result = ps.executeQuery();
            if(result.next()){
                new frmMain().show();
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Salah!");
                txtpass.setText("");
                txtnama.requestFocus();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
    
    }//GEN-LAST:event_inActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ex;
    private javax.swing.JButton in;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpass;
    private javax.swing.JButton up;
    // End of variables declaration//GEN-END:variables
}
